name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io jq

      - uses: lowlighter/metrics@latest
        with:
          filename: .github/metrics_renders/github-metrics.svg
          token: ${{ secrets.MATRIC_SECRET }}              # Make sure this PAT is set and has correct scopes
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_lines: yes
          plugin_habits: yes

      - name: Commit generated metrics
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .github/metrics_renders/github-metrics.svg
          git commit -m "chore: update GitHub Metrics" || echo "No changes to commit"
          git push
