name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]  
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_lines: yes
          plugin_habits: yes
